name: hello world

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Say hello
        run: echo "Hello, world!"